#!/usr/bin/env groovy
/**
  This is the Jenkinsfile for kicking off the ansible playbook to pull
  data from elasticsearch to kafka nightly.
 */
ansiColor('xterm') {
  timestamps {
        node('dhslave') {

          configFileProvider(
          [configFile( fileId: 'kubeconfig', variable: 'KUBECONFIG')]){
	      stage('Pull Git Repositories') {
                checkout_playbook_repo()
              }
              stage('Trigger Playbook') {
                start_deploy_spark()
              }
          }
        }
  }
}

def checkout_playbook_repo() {
    checkout poll: false, scm: [
      $class: 'GitSCM',
      branches: [[name: "*/master"]],
      doGenerateSubmoduleConfigurations: false,
      submoduleCfg: [],
      userRemoteConfigs: [[url: 'https://gitlab.cee.redhat.com/data-hub/spark-analytics.git']]
    ]
}

def start_deploy_spark() {
  try {
      sh '''
virtualenv $WORKSPACE/venv
source $WORKSPACE/venv/bin/activate

set -ex
cd ansible
ansible-playbook playbooks/spark-pipeline-deployment.yaml -vvv -i inventory -e "kubeconfig=$KUBECONFIG spark_project=${NAMESPACE}"
'''

  } catch (err) {
    echo 'Exception caught, being re-thrown...'
    throw err
  }

}
