apiVersion: v1
kind: BuildConfig
metadata:
  labels:
    app: simple-pyspark
  name: simple-pyspark
spec:
  output:
    to:
      kind: ImageStreamTag
      name: simple-pyspark:latest
  runPolicy: Serial
  source:
    git:
      uri: https://gitlab.cee.redhat.com/emqiu/simple-spark-script.git
    type: Git
  strategy:
    sourceStrategy:
      env:
      - name: APP_FILE
        value: app.py
      - name: GIT_SSL_NO_VERIFY
        value: "true"
      forcePull: true
      from:
        kind: DockerImage
        name: docker-registry.engineering.redhat.com/aicoe/pyspark-base-image:final
    type: Source
  triggers:
  - type: ConfigChange
  - github:
      secret: simple-pyspark
    type: GitHub
  - generic:
      secret: spark-sample
    type: Generic
status:
  lastVersion: 0
